name: Destroy terraform infra

on:
  workflow_dispatch:

jobs:

  destroy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      
        - name: Clone Repo
          uses: actions/checkout@v4

        - name: Install Terraform
          uses: hashicorp/setup-terraform@v3
          
        - name: Get Short SHA value
          uses: benjlevesque/short-sha@v3.0
          id: short-sha
          with:
            length: 6

        - name: Configure AWS Access keys
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: eu-west-1
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}

        - name: Initialize Terraform
          run: terraform init

        - name: Validate Terraform COnfiguration
          run: terraform validate

        - name: Destroy all terraform infra
          run: terraform destroy --auto-approve







